meta: OBJECT_VIDEO_V0

parent_dir: 'FILLED BY SUPER PROJECT (super_config_source)'
name: 'FILLED BY SUPER PROJECT (super_config_source)'

preproc_config_template:
    project:
        type: 'PreprocProj'
        project_dir: 'FILLED BY SUPER PROJECT'
        pipeline: 
        - 'PreprocessReconTask'
        - 'InitReconLocTask'

    preprocess_recon_config:
        src_mode: 'videoid_frameid'
        src_type: 'obj_video_list'
        src_config:
            camera_model: 3
            focal_length: 'FILLED BY SUPER PROJECT (super_config_source)'
            src_video_list: 'FILLED BY SUPER PROJECT (super_config_source)'
            ss_list: 'FILLED BY SUPER PROJECT (super_config_source)'
            to_list: 'FILLED BY SUPER PROJECT (super_config_source)'
            fps_list: 'FILLED BY SUPER PROJECT (super_config_source)'
        stage_list: []
        # -   stage_type: 'DownsizeStage'
        #     stage_config:
        #         power_factor: 1

recon_config_template:
    is_scene: false
    project:
        type: 'ReconProj'
        project_dir: 'FILLED BY SUPER PROJECT'
        name: 'FILLED BY SUPER PROJECT'
        n_thread: 20
        process_prio: 2
        pipeline:
        - 'SfM_INITIALIZE'
        - 'SfM_COMPUTE_FEATURES'
        - 'GENERATE_PAIR_LIST'
        - 'SfM_COMPUTE_MATCHES'
        - 'SfM_INCREMENTALLY_RECONSTRUCT_V2'
        - 'SfM_FILTER_RESULTS'
        - 'SfM_EXPORT_RESULTS'
        - 'MVS_DENSIFY_POINT_CLOUD'
        - 'MVS_RECONSTRUCT_MESH'
        - 'MVS_REFINE_MESH'
        - 'MVS_TEXTURE_MESH'

    images:
        img_prj_dir: 'FILLED BY PREPROC'

    sfm:
        recon_alg: 'incremental'
        camera_model: 'FILLED BY PREPROC'
        focal_length: 'FILLED BY PREPROC'

        pair_list:
            generator_type: 'backbone_detail'
            generator_config:
                backbone_frame_gap: 10

        feature_matching:
            describer: 'AKAZE_FLOAT'
            describer_preset: 'ULTRA'
            geometric_model: 'f'  
            nnd_ratio: 0.8
            match_alg: 'FASTCASCADEHASHINGL2'

        reconstruction:
            calc_intrinsics: 'ADJUST_ALL'
            init_img: ['', '']

        filter:
            filter_type: 'cov'
            filter_config:
                contamination: 0.2

    mvs:
        resol_limit: [640, 3200]

        densify_pcl:
            resol_lv: 1
            fuse_mode: 0
            number_views: 0

        reconstruct_mesh:
            min_point_distance: 0.0
            free_space_support: 1
            decimate: 1

        refine_texture:
            scales: 2
            resol_lv: 0
            decimate: 0.5
