meta: SCENE_V0

parent_dir: 'FILLED BY SUPER PROJECT (super_config_source)'
name: 'FILLED BY SUPER PROJECT (super_config_source)'

preproc_config_template:
    project:
        type: 'PreprocProj'
        project_dir: 'FILLED BY SUPER PROJECT'
        pipeline: 
        - 'PreprocessLocTask'
        - 'PreprocessReconTask'
        - 'PersonMaskTask'
        - 'SlicingTask'
        - 'InitReconLocTask'

    preprocess_loc_config:
        src_mode: 'frameid_camid'
        src_type: 'insta360equirect'
        src_config:
            # camera_model: NOT_USED
            # focal_length: NOT_USED
            src_dir: 'FILLED BY SUPER PROJECT (super_config_source)'
            ss: 'FILLED BY SUPER PROJECT (super_config_source)'
            to: 'FILLED BY SUPER PROJECT (super_config_source)'
            fps: 10
        stage_list:
        -   stage_type: 'CubemapStage'
            stage_config: {}
    
    preprocess_recon_config:
        src_mode: 'frameid_camid'
        src_type: 'insta360'
        src_config:
            # camera_model: NOT_USED
            # focal_length: NOT_USED
            src_dir: 'FILLED BY SUPER PROJECT (super_config_source)'
            ss: 'FILLED BY SUPER PROJECT (super_config_source)'
            to: 'FILLED BY SUPER PROJECT (super_config_source)'
            fps: 2
        stage_list:
        -   stage_type: 'RotateStage'
            stage_config: {}
        -   stage_type: 'DefisheyeStage'
            stage_config: 
                k_d_npz: '/volume/cpl-dev/sfm/insta360pro2_calib/insta360pro2_intrisics.npz'
        -   stage_type: 'DownsizeStage'
            stage_config:
                power_factor: 1

    person_mask_config:
        person_label: 13
        MAX_INPUT_SIZE: [257, 257]
        MODEL_PATH: '/volume/smart-city-nas12/sfm/person_mask_model/deeplabv3_mnv2_ade20k_train_2018_12_03/frozen_inference_graph.pb'

    slicing_config:
        slice_length: 30
        overlap_length_list: [[1, 5], [2, 3]]

recon_config_template:
    is_scene: true
    project:
        type: 'ReconProj'
        project_dir: 'FILLED BY SUPER PROJECT'
        name: 'FILLED BY SUPER PROJECT'
        n_thread: 20
        process_prio: 2
        n_lense_for_rot: 0
        pipeline:
        - 'SfM_INITIALIZE'
        - 'SfM_COMPUTE_FEATURES'
        - 'GENERATE_PAIR_LIST'
        - 'SfM_COMPUTE_MATCHES'
        - 'SfM_INCREMENTALLY_RECONSTRUCT_V2'
        - 'SfM_REFINE_CAMPOSE'
        - 'SfM_INCREMENTALLY_RECONSTRUCT_REFINE'
        - 'SfM_FILTER_RESULTS'
        - 'SfM_EXPORT_RESULTS'
        - 'SfM_EXPAND_FPS'
        - 'MVS_DENSIFY_POINT_CLOUD'
        - 'MVS_RECONSTRUCT_MESH'
        # - 'MVS_REFINE_MESH'
        # - 'MVS_TEXTURE_MESH'
        # - 'SIMPLIFY_MESH'
        # - 'CORRECT_LEVEL'
        - 'GENERATE_FOOTPRINTS'
        # - 'ZERO_INITIAL_POSE'
        - 'EXPORT_MODEL_TO_APP'

    images:
        img_prj_dir: 'FILLED BY PREPROC'

    sfm:
        recon_alg: 'incremental'
        camera_model: 'FILLED BY PREPROC'
        focal_length: 'FILLED BY PREPROC'
        loc_camera_model: 'FILLED BY PREPROC'
        loc_focal_length: 'FILLED BY PREPROC'

        pair_list:
            generator_type: 'slice_rig'
            generator_config:
                rig_type: 'ring_window'
                num_rig_views: 6
                near_frame: 5

        feature_matching:
            describer: 'AKAZE_FLOAT'
            describer_preset: 'ULTRA'
            geometric_model: 'f'  
            nnd_ratio: 0.8
            match_alg: 'FASTCASCADEHASHINGL2'

        reconstruction:
            calc_intrinsics: 'ADJUST_ALL'
            init_img: ['', '']

        campose_refiner:
            refiner_type: 'rig_center'
            refiner_config:
                num_rig_views: 6
        
        filter:
            filter_type: 'cov'
            filter_config:
                contamination: 0.05

        expand_fps:
            threshold: 5
            intrinsics_sub: separate

    mvs:
        resol_limit: [640, 3200]

        densify_pcl:
            resol_lv: 1
            fuse_mode: 0
            number_views: 0

        reconstruct_mesh:
            min_point_distance: 0.0
            free_space_support: 1
            decimate: 0.25
            
        # refine_texture:
        #     scales: 2
        #     resol_lv: 0
        #     decimate: 0.5

    # simplify:
    #     n_clusters: 50
    #     normal_test_thr: 0.966
    #     bounding_box_buffer: 0.05
    #     seg_size_thr: [20, 60, 1420]

    # correct_lv:
    #     normal_test_thr: 0.9
    #     sigma_fac: 2.0
    #     correctness_thr: 1

    gen_footprints:
        r_floor_cut: 0.5


loc_config_template:
    project:
        type: 'LocProj'
        name: 'FILLED BY SUPER PROJECT'
        project_dir: 'FILLED BY SUPER PROJECT'
        force_new_project_dir: false
        n_thread: 20
        process_prio: 2
        n_lense_for_rot: 0 # The lense number (0-based) whose rotation should be used as "merged rotation"
        pipeline:
            - 'SfM_MATCH_SUB2MAIN'
            - 'CALCULATE_TRANSFORMATION_SUB2MAIN'
            - 'APPLY_TRANSFORMATION_EXPORT_SUBS'

    transform:
        prj_dir_main: # 'recon project parent dir + name' for slice 001, 'loc project parent dir + name' for slice 002 onward
        data_dir_name_main: 'data_OUR_OWN_NAME_SLICE_NUMBER'
        prj_dir_sub: # 'recon project parent dir + name' for all slices
        data_dir_name_sub: 'data_OUR_OWN_NAME_SLICE_NUMBER'
        threshold: 5
        intrinsics_sub: 'separate'

    apply:
        overwrite_subs: false
